pipeline:
  name: iacm-ansible-plugin-test-pipeline-ansible
  identifier: iacmansibleplugintestpipelineansible
  projectIdentifier: default_project
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: Configure using Ansible
        identifier: Configure_using_Ansible
        description: ""
        type: IACM
        spec:
          infrastructure:
            type: KubernetesDirect
            spec:
              connectorRef: account.kubernetes
              namespace: harness-delegate-ng
              volumes: []
              serviceAccountName: kubernetes-delegate
              annotations: {}
              labels: {}
              automountServiceAccountToken: true
              nodeSelector: {}
              containerSecurityContext:
                capabilities:
                  drop: []
                  add: []
              os: Linux
              hostNames: []
          execution:
            steps:
              - step:
                  type: Plugin
                  name: Plugin_1
                  identifier: Plugin_1
                  spec:
                    connectorRef: account.dockerconnector
                    image: plugins/aws-oidc
                    settings:
                      iamRoleArn: arn:aws:iam::282764120287:role/harness-oidc-role
                      role_session_name: foo
                      duration: 3600
              - step:
                  type: IACMAnsiblePlugin
                  name: IACMAnsiblePlugin_1
                  identifier: IACMAnsiblePlugin_1
                  spec:
                    command: run
                    image: pkg.harness.io/n5dbefl9s4-ibnocsk8gbg/abc/harness-ansible-with-awscli@sha256:6ff48c46c964169ee7a30d625e863e8e0a0ca4ad3e80bd43735ea8b5b5be4d6d
                    connectorRef: account.harnessdockerregistry
                  playbooks:
                    - iacmansibletestplaybook
                  inventories:
                    - iacmansibletestinventory
                  timeout: 1h
          playbooks:
            - iacmansibletestplaybook
          inventories:
            - iacmansibletestinventory
        tags: {}
