pipeline:
  name: iacm-ansible-plugin-test-pipeline-ansible
  identifier: iacmansibleplugintestpipelineansible
  projectIdentifier: default_project
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: Configure using Ansible
        identifier: Configure_using_Ansible
        description: ""
        type: IACM
        spec:
          infrastructure:
            type: KubernetesDirect
            spec:
              connectorRef: account.kubernetes
              namespace: harness-delegate-ng
              volumes: []
              serviceAccountName: kubernetes-delegate
              annotations: {}
              labels: {}
              automountServiceAccountToken: true
              nodeSelector: {}
              containerSecurityContext:
                capabilities:
                  drop: []
                  add: []
              os: Linux
              hostNames: []
          execution:
            steps:
              - step:
                  type: Plugin
                  name: Plugin_1
                  identifier: Plugin_1
                  spec:
                    connectorRef: account.dockerconnector
                    image: plugins/aws-oidc
                    settings:
                      iamRoleArn: arn:aws:iam::282764120287:role/harness-oidc-role
                      role_session_name: foo
                      duration: 3600
              - step:
                  type: IACMAnsiblePlugin
                  name: IACMAnsiblePlugin_1
                  identifier: IACMAnsiblePlugin_1
                  spec:
                    command: run
                  playbooks:
                    - iacmansibletestplaybook
                  inventories:
                    - iacmansibletestinventory
                  timeout: 1h
              - step:
                  type: Run
                  name: Run_1
                  identifier: Run_1
                  spec:
                    connectorRef: account.dockerconnector
                    image: amazon/aws-cli:latest
                    shell: Bash
                    command: |-
                      export AWS_ACCESS_KEY_ID="<+steps.Plugin_1.output.outputVariables.AWS_ACCESS_KEY_ID>"
                      export AWS_SECRET_ACCESS_KEY="<+steps.Plugin_1.output.outputVariables.AWS_SECRET_ACCESS_KEY>"
                      export AWS_SESSION_TOKEN="<+steps.Plugin_1.output.outputVariables.AWS_SESSION_TOKEN>"

                      echo "${AWS_ACCESS_KEY_ID}XXX"
                      echo $AWS_ROLE_ARN
                      echo $AWS_SECRET_ACCESS_KEY
                      echo $AWS_SESSION_TOKEN

                      echo "<+steps.Plugin_1.output.outputVariables.AWS_ACCESS_KEY_ID>" > /harness/proof.txt
                      echo "<+steps.Plugin_1.output.outputVariables.AWS_SECRET_ACCESS_KEY>"
                      echo "<+steps.Plugin_1.output.outputVariables.AWS_SESSION_TOKEN>"


                      sleep 100000000
                    envVariables:
                      AWS_ACCESS_KEY_ID: <+steps.Plugin_1.output.outputVariables.AWS_ACCESS_KEY_ID>
                      AWS_SECRET_ACCESS_KEY: <+steps.Plugin_1.output.outputVariables.AWS_SECRET_ACCESS_KEY>
                      AWS_SESSION_TOKEN: <+steps.Plugin_1.output.outputVariables.AWS_SESSION_TOKEN>
                      SUPPORT_DEBUG: "true"
          playbooks:
            - iacmansibletestplaybook
          inventories:
            - iacmansibletestinventory
        tags: {}
